tasks:
  - init: |
      nvm install v12.18.1
      yarn cache clean
      yarn && yarn build
    openMode: split-right
    name: botpress
  - init: |
      nvm install v12.18.1
      cd /workspace/botpress-studio
      yarn
    command: |
      cd /workspace/botpress-studio
      nvm install v12.18.1
      yarn watch
    openMode: split-right
    name: studio
  - init: |
      cd /workspace/botpress/modules/basic-skills
      nvm install v12.18.1
      yarn
    command: |
      cd /workspace/botpress/modules/basic-skills
      nvm install v12.18.1
      yarn watch
    openMode: split-right
    name: qorus-skill
vscode:
  extensions:
    - oderwat.indent-rainbow
    - mintlify.document
    - streetsidesoftware.code-spell-checker
    - tombonnike.vscode-status-bar-format-toggle
    - github.copilot
    - fivepointseven.node-version
    - kejun.devtoys
    - esbenp.prettier-vscode
    - visualstudioexptteam.vscodeintellicode
    - styled-components.vscode-styled-components
    - kejun.devtoys
additionalRepositories:
  - url: https://github.com/qoretechnologies/botpress-studio.git
workspaceLocation: /workspace/botpress/botpress.code-workspace
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addComment: true
    addBadge: true
    addLabel: prebuilt-ready
