tasks:
  - init: |
      nvm install v12.18.1
      yarn cache clean
      yarn && yarn build
    command: yarn watch
    openMode: split-right
    name: botpress
  - init: |
      nvm install v12.18.1
      cd /workspace
      git clone https://github.com/botpress/studio.git
      cd studio/
      yarn cache clean
      yarn && yarn build
    command: cd /workspace/studio && yarn watch
    openMode: split-right
    name: studio
vscode:
  extensions:
    - esbenp.prettier-vscode@5.7.1:GDba64T6G+TUi1qmc6BE3A==
    - oderwat.indent-rainbow@7.4.0:fDVCkGVYd1R2lfcs1tHk+Q==
    - humao.rest-client@0.24.4:zy4YO0p/vGcDbgPap4k4+A==
    - wayou.vscode-todo-highlight@1.0.4:TEjqQVt71hdvHUZA7eWgHA==

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addComment: true
    addBadge: true
    addLabel: prebuilt-ready
